import React from 'react';

const AmlPolicy = () => {
    return (
        <div className='lg:ml-5 px-5 lg:mt-10 text-white'>
            <h1 className='font-semibold mb-2 mt-2 text-2xl'></h1>
            <div>
                <h1 className='font-semibold mb-2 text-2xl'>What is money laundering?</h1>
                <p>
                    Money laundering is the act of concealing illegally obtained currency and legalizing the source of the currency. We follow strict laws and prohibit any employee or agent from intentionally participating in or attempting to participate in any activities related to money laundering. Our anti-money laundering policy strengthens the protection of investors, investor security payment procedures, and customer security services.
                </p>
            </div>
            <div>
                <h1 className='font-semibold mb-2 mt-2 text-2xl'>Identity document</h1>
                <p>The first level of prevention for money laundering is the complex “know your customer” (KYC) verification process. To ensure compliance with standard anti-money laundering regulations, we require you to submit the following documents:

                    Identification materials: a clear photocopy of the front and back of a government-issued photo ID, such as a valid passport, driving license, or your national ID card.
                    Proof of Residence: An official document issued within the last 3 months and clearly indicating the name and address you used when registering with UFX. It can be a property bill (such as a water/electricity/fixed-line bill) or a bank statement. Please ensure that the submitted documents include the following:
                    your real name
                    Full residential address
                    Date of issuance (within 3 months)
                    Name of issuing organization with official logo or seal
                    Copy of the front and back of your credit card: To ensure privacy and security, you only need to ensure that the last 4 digits of your credit card are clearly visible. You can also cover the last 3 digits (verification code) on the back of the card.
                    Please note that in view of the different regulatory requirements in some countries, we may require you to submit additional documents.

                    You will not be able to conduct transactions until we receive and approve your "know your customer" identification documents. Any transactions opened before your account is approved may be cancelled. Any losses or profits generated by these transactions will also be cancelled and removed from your account.</p>
            </div>
            <div>
                <h1 className='font-semibold mb-2 mt-2 text-2xl'>monitor</h1>
                <p>We do not accept third-party payments. All payments must be made in your own name and in accordance with the identity documents submitted. The anti-money laundering regulatory policy stipulates that all withdrawn funds must be returned to their original source of funds. This means that if you deposit funds via bank transfer, the funds withdrawn must be returned to the same account when the transfer was made. Similarly, if you use a credit card to deposit funds, the funds you withdraw must be returned to this credit card.

                    Under no circumstances will we accept cash deposits or cash withdrawals.

                </p>
            </div>
            <div>
                <h1 className='font-semibold mb-2 mt-2 text-2xl'>Report</h1>
                <p>Anti-money laundering regulations require us to monitor and track suspicious transactions and report to relevant law enforcement agencies. If we believe that the transfer of funds is in any way related to criminal activities or money laundering, we have the right to refuse the transfer of funds at any stage. The law prohibits us from telling customers about submitting reports of suspicious behavior to law enforcement agencies.</p>
            </div>
            <div>
                <h1 className='font-semibold mb-2 mt-2 text-2xl'>Source of income</h1>
                <p>
                    The company must keep the customer's deposit documents and comply with anti-money laundering rules and regulations. According to the company's discretion, you should fill out the "source of income" form, indicate your source of income, and attach relevant supporting documents to prove your statement. If you do not provide sufficient information and evidence, and cannot prove your statement and deposit, the company will require you to provide further supporting documents.
                </p>
                <p>
                    If you fail to provide the required supporting documents within a reasonable time frame, your account will be locked.
                    If you have any questions, please send an email to: compliance@yebet.com
                </p>
            </div>
        </div>
    );
};

export default AmlPolicy;